### ISSUE TITLE
2MB limit

### ISSUE THREAD

**Issue by hicane0** [samyuu/TaikoSwitchDataTableDecryptor#1]
Thanks for your tools!  you did a great job! And I would like to ask if it is possible to break the 2MB limit? 

Another strange thing is that the game has a limit on the number of songs (500 in the latest version, the game will only play songs with [uniquId] between 0-499), (in earlier versions this number was 200), I don't know how to try to break it, it's unlikely that the file in the **datatable directory** determines this number. I think it might be in the **main file** which is in the **exefs directory**

Have you do any research in this? I'm not very good at decompiling, I tried to change this number limit but failed ....T_T

**Comment by samyuu** [comment]
Hello! Conceptually speaking, increasing the datatable filesize limit *seems* very possible.
There are two static `byte array[0x200000]` in the `.bss` section of the ELF executable (which is where statically allocated variables are stored) that are used for temporarily decrypting/decompressing the datatable file content into before being parsed.
I have the strong intuition that it *should be possible* to increase the size of this section, update the code to point to the (now enlarged) end part and update the corresponding array sizes to match (which are loaded as constants directly into registers).

Theoretically this would allow increasing the size to another larger (but still fixed size) limit without *too much* work. 
Problem is, I'm not actually sure how one would pull this off in practice. I'm *assuming* the section sizes are defined somewhere in the ELF header and increasing the allocated size would be as simple as editing it there but... shrug, I usually deal with windows EXEs

A more robust solution would of course be to dynamically allocate the right amount of memory in place and roll with that.
That would require a bit of ARM assembly but otherwise shouldn't be too bad.
*Except another problem with this* is that there isn't really any space to actually inject *new code* into.
One workaround I can think of (and that I have done before somewhere else, although for x86) is to abuse the fact that functions are always aligned to 16 byte boundaries which leaves the padding bytes inbetween as free executable space.
So one way to inject new code would be to insert a JMP (or rather a "branch" in this case) from the original function into the *padding* of *another function*, write **parts** of the new code there then jump directly to the *next padding* and so on until eventually returning to the original function. 
Doing it this way would be incredibly tedious but at least theoretically possible (and of course would also have to be repeated for every game region/update).

Another important thing to note also is that an easy way to reduce the json file size would be to *remove all whitespace* (minifying it) and (I haven't tried this) *but* also try to remove all of the fields that are either `0`s or empty strings `""` since presumably (*I would hope*) those would be default initialized in case they are omitted making them redundant. 

I don't know what the current status on the ID limit for the switch release is (I believe at least for some of the other taiko games it has been somewhat solved)
but in case you don't already know, there's a [taiko modding discord server](https://discord.gg/HFm37aA5zr) so feel free to also try your luck there if you'd like.
I don't really do too much modding myself directly and mostly only work on the tooling side of things

**Comment by hicane0** [comment]
Thank you very much for your reply, according to your suggestion, I deleted some unnecessary information and empty strings, and successfully compressed the json to less than 2MB

About the limitation of the number of songs, I am going to go to the discord channel to know the current status, thank you for your suggestion and wish you all the best~
